environment:
  JAVA_HOME : C:\Program Files\Java\jdk1.7.0\

install:
  - mkdir aa
  - rmdir aa
  - ECHO Y | CACLS C:\projects\blueprints\blueprints-neo4j2-graph\ /g %username%:F
  - mvn install -DskipTests=true


test_script:
  - mvn test

build: off